spring:
  datasource:
    hikari:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:mariadb://210.113.0.140:3316/transdocu
      username: transdocu
      password: qwer!@#$
      idle-timeout: 8000
      connection-timeout: 8000

file:
  upload:
    path: ./uploads

server:
  port: 8089
  servlet:
    context-path: /document


scheduler:
  cron: "*/30 * * * * *" # 30초마다 실행
  enable : true